---
deployment:
  tasks:
    - export DEPLOYPATH=/home/powervan/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp server.py $DEPLOYPATH
    - /bin/cp translations.js $DEPLOYPATH